name: Bug Report
description: Report something that isn't working correctly
title: "[Bug]: "
labels: ["bug", "status:todo"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's broken? Be specific.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Exact steps to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens? Include error messages verbatim.
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Screenshots, stack traces, console output, network logs
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "P0 — Critical / data loss / security"
        - "P1 — High / blocks core workflow"
        - "P2 — Medium / workaround exists"
        - "P3 — Low / cosmetic"
      default: 2
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, version, deployment target
      placeholder: "macOS 14, Chrome 120, staging"
    validations:
      required: false
