name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature", "status:todo", "needs-spec"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Who is affected?
      placeholder: "As a [user], I need [capability] because [reason]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What should happen? What does success look like?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this is done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "P0 — Critical"
        - "P1 — High"
        - "P2 — Medium"
        - "P3 — Low"
      default: 2
    validations:
      required: true

  - type: input
    id: epic
    attributes:
      label: Epic (issue number)
      description: Parent epic if applicable
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Context
      description: Links, screenshots, prior art, related issues
    validations:
      required: false
